language: csharp
solution: NtfsSharp.sln
matrix:
  include:
    - dotnet: 1.0.4
      mono: none
    - mono: latest
install:
  - nuget restore NtfsSharp.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Mono NtfsSharp.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./NtfsSharp.Tests/bin/Mono/NtfsSharp.Tests.dll
