version: 1.0.{build}
image: Visual Studio 2017

before_build:
- ps: nuget restore

build:
  project: NtfsSharp.Tests/
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:  
    secure: N0XNTb1xnn0yOFDTnjoKu1vRSIVQvcO9Pt9v0If0LtG6TjZ1iE1Rn8ur5h6sU1Yz
after_test: 
  # generate report for NUnit testing framework:
  - cmd: packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe" -targetargs:"/domain:single NtfsSharp.Tests\bin\Debug\NtfsSharp.Tests.dll" -output:coverage.xml
  - cmd: packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml