version: 1.0.{build}
image: Visual Studio 2019

before_build:
  - ps: dotnet add NtfsSharp.Tests package OpenCover --version 4.7.922
  - ps: dotnet add NtfsSharp.Tests package coveralls.io --version 1.4.2
  - ps: dotnet restore --packages ./packages NtfsSharp.sln

build:
  project: NtfsSharp.Tests/
  verbosity: minimal

environment:
  COVERALLS_REPO_TOKEN:  
    secure: N0XNTb1xnn0yOFDTnjoKu1vRSIVQvcO9Pt9v0If0LtG6TjZ1iE1Rn8ur5h6sU1Yz
  APPVEYOR_RDP_PASSWORD: a3vAE5MjPj6eA4Mh

test_script:
  # generate report for NUnit testing framework:
  - cmd: c:\projects\ntfssharp\packages\opencover\4.7.922\tools\OpenCover.Console.exe -register:user -target:"c:\Program Files\dotnet\dotnet.exe" -targetargs:"test" -output:c:\projects\ntfssharp\coverage.xml
after_test: 
  - cmd: c:\projects\ntfssharp\packages\coveralls.io\1.4.2\tools\coveralls.net.exe --opencover "c:\projects\ntfssharp\coverage.xml"
  
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))