# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore /p:EnableWindowsTargeting=true NtfsSharp.sln
    - name: Build
      run: dotnet build --no-restore /p:EnableWindowsTargeting=true /p:Configuration=Testing NtfsSharp.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal
